import "@fortawesome/fontawesome-free/css/all.min.css";

const icon = {
    default: " fa-solid fa-bars",
    column : "fa fa-columns",
    house: " fa-solid fa-house",
    user: " fa-solid fa-user",
    tick: " fa-solid fa-check",
    magnifyingglass: " fa-solid fa-magnifying-glass",
    download: " fa-solid fa-download",
    phone: " fa-solid fa-phone",
    envelope: " fa-solid fa-envelope",
    location: " fa-solid fa-location-dot",
    star: " fa-solid fa-star",
    heart: " fa-solid fa-heart",
    arrowRight: " fa-solid fa-arrow-right",
    arrowUp: " fa-solid fa-arrow-up",
    arrowDown: " fa-solid fa-arrow-down",
    arrowLeft: " fa-solid fa-arrow-left",
    remark: " fa-solid fa-comment",
    pen: " fa-solid fa-pen",
    calender: " fa-solid fa-calender-days",
    cloud: " fa-solid fa-cloud",
    paperclip: " fa-solid fa-paperclip",
    bell: " fa-solid fa-bell",
    clipboard: " fa-solid fa-clipboard",
    list: " fa-solid fa-list",
    mapAlias: " fa-solid fa-map-pin",
    penSquare: "fa-solid fa-pen-to-square",
    trash: "fa-solid fa-trash",
    refresh: "fa-solid fa-refresh",
    rupees: "fas fa-rupee-sign",
    users: "fa-solid fa-users",
    addressCard:"fa-regular fa-address-card",
    attendance: "fa-solid fa-clipboard-list",
    examForm: "fa-solid fa-file-circle-plus",
    grievanceSubmit: "fa-solid fa-file-circle-exclamation",
    grievanceTracking: "fa-solid fa-magnifying-glass",
    fee: "fa-solid fa-money-check-dollar",
    calendar: "fa-solid fa-calendar",
    plus: "fa-solid fa-plus",
    compass: "fa-regular fa-compass",
    video: "fa-solid fa-clapperboard",
    message: "fa-brands fa-facebook-messenger",
    heart: "fa-regular fa-heart",
    plus: "fa-solid fa-square-plus",
    user: "fa-regular fa-user",

} 
export default icon;
